version: "3.9"
networks:
    default:
        name: data-collection-network
        external: true
services:
    data-collection:
        image: data-collection
        container_name: data-collection
        volumes:
            - ../secrets:/secrets
            - ../data_collection:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: ../secrets/data-service-account.json
            GCP_PROJECT: "ac215-project"
            GCP_ZONE: "us-central1-a"
            GCS_BUCKET_NAME: "s2s_data"