version: "3.9"
networks:
    default:
        name: feature-extraction-network
        external: true
services:
    feature-extraction:
        image:  hzhu98/feature-extraction:latest
        container_name: feature-extraction
        volumes:
            - ../secrets:/secrets
            - ../feature_extraction:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: ../secrets/data-service-account.json
            GCP_PROJECT: "ac215-project"
            GCP_ZONE: "us-central1-a"
            GCS_BUCKET_NAME: "s2s_data_new"